[database]
driver="postgres"
datasource="user=automation-executor dbname=automation-executor sslmode=disable password=12345 host=localhost"

[storage]
workspaces-location="/home/pablintino/Desktop/test-ws"